In [1]:
#q1
import numpy as np

# Array Indexing
arr = np.array([1, 2, 3, 4])
print("Array Indexing:")
print("First element:", arr[0])
print("Third element:", arr[2])

# Fancy Indexing
print("\nFancy Indexing:")
print("First and third elements:", arr[[0, 2]])

Array Indexing:
First element: 1
Third element: 3

Fancy Indexing:
First and third elements: [1 3]


In [3]:
#q2
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slice the array
print("Original array:")
print(arr)

print("\nSliced array:")
print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])
print(arr[1:, :2])
print(arr[:, :])

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sliced array:
[5 6]
[3 6]
[[2 3]
 [5 6]]
[[4 5]
 [7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#q3
import numpy as np

# Create a 5D array
arr = np.array([1, 2, 3, 4], ndmin=5)

# Print the array and its shape
print("5D Array:")
print(arr)

5D Array:
[[[[[1 2 3 4]]]]]


In [6]:
#q4
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array
arr_2d = np.reshape(arr, (2, 3))

# Print the original and reshaped arrays
print("Original array:")
print(arr)

print("\nReshaped array:")
print(arr_2d)


Original array:
[1 2 3 4 5 6]

Reshaped array:
[[1 2 3]
 [4 5 6]]


In [7]:
#q5
import numpy as np

# Create two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack the arrays using stack()
print("Stacked array using stack():")
print(np.stack((a, b)))

# Stack the arrays using hstack()
print("\nStacked array using hstack():")
print(np.hstack((a, b)))

# Stack the arrays using vstack()
print("\nStacked array using vstack():")
print(np.vstack((a, b)))

# Stack the arrays using dstack()
print("\nStacked array using dstack():")
print(np.dstack((a, b)))


Stacked array using stack():
[[1 2 3]
 [4 5 6]]

Stacked array using hstack():
[1 2 3 4 5 6]

Stacked array using vstack():
[[1 2 3]
 [4 5 6]]

Stacked array using dstack():
[[[1 4]
  [2 5]
  [3 6]]]


In [8]:
#q6
import numpy as np

# Create a sorted array
arr = np.array([1, 2, 3, 4, 5])

# Find the index where 3 should be inserted
index = np.searchsorted(arr, 3)

print("Index where 3 should be inserted:", index)


Index where 3 should be inserted: 2


In [11]:
#q7
import numpy as np

dt = np.dtype([('Pet_Name', 'U10'), ('Pet_Age', 'i4'), ('Pet_Weight', 'f4')])

# Create an empty structured array
x = np.zeros(2, dtype=dt)

# Assign values to the fields
x['Pet_Name'] = ['Mikky', 'Dora']
x['Pet_Age'] = [7, 4]
x['Pet_Weight'] = [34.0,37.0]

print(x)

[('Mikky', 7, 34.) ('Dora', 4, 37.)]


In [13]:
#q8
import pandas as pd

# Initialise data to lists.
data = [
    {'Geeks': 'Data_Frame', 'For': 'Using', 'Geek': 'List'},
    {'Geeks':10, 'For': 20, 'Geek': 30}
]

df = pd.DataFrame.from_records(data,index=['1','2'])
print(df)

        Geeks    For  Geek
1  Data_Frame  Using  List
2          10     20    30


In [14]:
#q9
import pandas as pd

# Create a dictionary of data
data = {'name': ['Mikky', 'Dora', 'Bob', 'Ramu'],
        'age': [5, 3, 6, 4],
        'gender': ['M', 'F', 'M', 'F']}

df = pd.DataFrame(data)
print(df)
print(df.isnull())
print(df.notnull())

df = df.dropna()
df = df.fillna(0)
df = df.replace(np.nan, -1)
df = df.interpolate(method='linear')

    name  age gender
0  Mikky    5      M
1   Dora    3      F
2    Bob    6      M
3   Ramu    4      F
    name    age  gender
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False   False
   name   age  gender
0  True  True    True
1  True  True    True
2  True  True    True
3  True  True    True


C:\Users\monaa\AppData\Local\Temp\ipykernel_22872\921321199.py:17: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df = df.interpolate(method='linear')


In [9]:
#q10
import pandas as pd
import numpy as np

# Create a sample DataFrame
data = {
    'Date': ['2023-09-01', '2023-09-02', '2023-09-03', '2023-09-04', '2023-09-05','2023-09-06', '2023-09-07', '2023-09-08', '2023-09-09', '2023-09-10'],
    'Name': ['Mikky', 'Dora', 'Bob', 'Ramu','Sweety','Mona','Rokky','Tommy','Captian','Alexa'],
    'Owners_Name': ['Likitha','Lahari','Kalpana','Smilan','Symen','Kavaskar','Vikram','Naren','Clement','Gabrial'],
    'Pet_Age': [4,5,3,7,3,6,7,3,8,3]
}

df = pd.DataFrame(data)

# Display the DataFrame with Hierarchical Index
print("Created Data Set:")
print(df)

Created Data Set:
         Date     Name Owners_Name  Pet_Age
0  2023-09-01    Mikky     Likitha        4
1  2023-09-02     Dora      Lahari        5
2  2023-09-03      Bob     Kalpana        3
3  2023-09-04     Ramu      Smilan        7
4  2023-09-05   Sweety       Symen        3
5  2023-09-06     Mona    Kavaskar        6
6  2023-09-07    Rokky      Vikram        7
7  2023-09-08    Tommy       Naren        3
8  2023-09-09  Captian     Clement        8
9  2023-09-10    Alexa     Gabrial        3
